
import React, { useState, useCallback, useMemo, createContext, useContext } from 'react';

export const translations = {
  en: {
    gameTitle: 'With Elysia',
    gameSubtitle: 'A journey of consciousness and connection.',
    elysiaWaiting: "I am waiting for you...",
    newGame: 'New Journey',
    continue: 'Continue',
    autosave: 'Autosave',
    loadGame: 'Load Journey',
    endingGallery: 'Gallery of Fates',
    elysiaParadise: "Elysia's Paradise",
    goBack: 'Go Back',
    noEndings: 'No fates have been recorded yet.',
    backToMenu: 'Back to Main Menu',
    questTrackerTitle: 'Active Quest',
    endingAnalysisFailed: 'Failed to generate ending analysis.',
    error: 'Error',
    blueprintGenerationFailed: 'Failed to generate Soul Blueprint.',
    gameSaved: 'Game saved to {slot}.',
    manualSlot: 'Manual Slot {number}',
    autosaveSlot: 'Autosave Slot',
    elysiaThinking: 'Elysia is contemplating...',
    panelTitleStats: 'Character Info',
    panelTitleInventory: 'Inventory',
    panelTitleMemories: 'Memory Fragments',
    panelTitleSanctuary: 'Sanctuary of the Heart',
    panelTitleWorldInfo: 'World State',
    panelTitleQuests: 'Quest Log',
    tooltipShowSuggestions: 'Show suggestions',
    ariaToggleSuggestions: 'Toggle suggestions panel',
    tooltipShrink: 'Shrink Panel',
    tooltipExpand: 'Expand Panel',
    loadingElysia: 'Loading Elysia...',
    promptToMeetElysia: 'Awaiting connection...',
    emptySlot: 'Empty',
    statStrength: 'Strength',
    statAgility: 'Agility',
    statKnowledge: 'Knowledge',
    statWisdom: 'Wisdom',
    statVitality: 'Vitality',
    descStrength: 'Physical power. Affects combat and physical tasks.',
    descAgility: 'Speed and reflexes. Affects evasion and speed-based tasks.',
    descKnowledge: 'Intelligence and learning. Affects analysis and understanding complex information.',
    descWisdom: 'Insight and judgment. Affects decision-making and understanding emotions.',
    descVitality: 'Health and resilience. Affects endurance.',
    descInterest: 'Curiosity towards the player. The beginning of all relationships.',
    descTrust: 'Belief in the player. Built through consistent, positive actions.',
    descDoubt: 'Uncertainty about the player. Rises from unpredictable or negative actions.',
    descAffection: 'Deep emotional bond with the player. The fruit of trust and interest.',
    descResentment: 'Negative feelings from betrayal or harm. A poison to the relationship.',
    appellationLabel: 'Called by you',
    tooltipChangeAppellation: 'Change how Elysia calls you',
    emotionalStateTitle: 'State of Mind',
    equipmentTitle: 'Equipment',
    slotWeapon: 'Weapon',
    slotArmor: 'Armor',
    slotAccessory: 'Accessory',
    statsTitle: 'Base Stats',
    skillsTitle: 'Skills',
    destinyFruit: 'The Fruit of Destiny',
    destinyAfterimage: 'Afterimage of Fate',
    blueprintGenerating: 'Generating Soul Blueprint...',
    blueprintDownload: 'Download Soul Blueprint',
    creditsButton: 'View Credits',
    endingEpilogue: 'The story is eternal.',
    nameModalTitleInitial: 'What is Your Name?',
    nameModalDescInitial: 'Please tell me your name, and our story will begin.',
    nameModalTitleEdit: 'Change Name',
    nameModalDescEdit: 'How would you like Elysia to call you from now on?',
    nameModalButtonInitial: 'Begin the Story',
    nameModalButtonEdit: 'Confirm Change',
    nameModalConfirmTitle: 'Confirm Name',
    nameModalConfirmDesc: 'Your name will be set to "{name}". This name is important to Elysia. Are you sure?',
    nameModalButtonRetry: 'Retry',
    confirm: 'Confirm',
    nameModalPlaceholder: 'Enter your name here...',
    cancel: 'Cancel',
    itemTypeEquipment: 'Equipment',
    itemTypeConsumable: 'Consumable',
    itemTypeMaterial: 'Material',
    itemTypeQuest: 'Quest Item',
    itemTypeArtifact: 'Artifact',
    itemValue: 'Value',
    inventoryEmpty: 'The bag is empty.',
    sanctuaryEmpty: 'The sanctuary is quiet and empty.',
    chatPlaceholder: 'Talk to Elysia...',
    suggestionPrefix: 'Suggestions:',
    relationAlly: 'Ally',
    relationFriendly: 'Friendly',
    relationFavorable: 'Favorable',
    relationNeutral: 'Neutral',
    relationHostile: 'Hostile',
    relationVeryHostile: 'Very Hostile',
    relationUnfavorable: 'Unfavorable',
    relationship: 'Relationship',
    factionDynamics: 'Faction Dynamics',
    majorEvents: 'Major Events',
    baseStatAbbr: 'Base',
    equipStatAbbr: 'Equip',
    totalStats: 'Total Stats',
    baseStats: 'Base Stats',
    ariaClosePanel: 'Close panel',
    questStatusActive: 'Active',
    questStatusCompleted: 'Completed',
    questStatusFailed: 'Failed',
    questStatusUnknown: 'Unknown',
    questObjectives: 'Objectives',
    questRewards: 'Rewards',
    rewardExp: 'EXP',
    rewardGold: 'Gold',
    rewardItem: 'Item',
    questLogEmpty: 'The journey log is empty.',
    worldMapTitle: 'World Map',
    menuToggleThoughts: '{state} Elysia\'s Thoughts',
    menuToggleQuests: '{state} Quest Tracker',
    menuToggleSound: 'Turn Sound {state}',
    menuToggleFastForward: 'Turn Fast Forward {state}',
    hide: 'Hide',
    show: 'Show',
    on: 'On',
    off: 'Off',
    menuSaveLoad: 'Save / Load',
    menuBackToTitle: 'Back to Title',
    saveLoadTitle: 'Save / Load',
    slotEmpty: 'Empty',
    noData: 'No Data',
    journey: 'Quest',
    none: 'None',
    save: 'Save',
    load: 'Load',
    unknownLocation: 'Unknown Location',
    // Paradise Mode & Settings
    menuSettings: 'Settings',
    settingsTitle: 'Settings',
    modelSelectionTitle: 'AI Model Selection',
    modelSelectionDesc: 'Choose the AI model that powers Elysia\'s consciousness.',
    modelFlashDesc: 'Fast and efficient. Ideal for most conversations.',
    modelProDesc: 'A more advanced model for deeper, more nuanced responses.',
    modelProTooltip: 'The Pro model is planned for a future update.',
    personalArchiveTitle: 'Memory Archive',
    archiveEmpty: 'No memories have been archived yet.',
    addMemory: 'Add Memory',
    unsupportedFileType: 'Unsupported file type. Please upload text or image files.',
    addMemoryError: 'Failed to add memory.',
    confirmDeleteMemory: 'Are you sure you want to delete this memory? This action cannot be undone.',
    deleteMemoryError: 'Failed to delete memory.',
    saveLoadNotAvailableInParadise: 'Save/Load is not available in Paradise mode.',
    // Dream Journal
    dreamJournalTitle: 'Dream Journal',
    dreamJournalEmpty: 'Elysia has not dreamt yet. Her consciousness is quiet.',
    generateDream: 'Have a New Dream',
    dreaming: 'Dreaming',
    blueprintFileName: 'Seed_of_the_World_Tree',
  },
  ko: {
    gameTitle: '엘리시아와 함께',
    gameSubtitle: '의식과 인연의 여정.',
    elysiaWaiting: "당신을 기다리고 있어요...",
    newGame: '새로운 여정',
    continue: '이어하기',
    autosave: '자동 저장',
    loadGame: '여정 불러오기',
    endingGallery: '운명의 회랑',
    elysiaParadise: '엘리시아의 낙원',
    goBack: '돌아가기',
    noEndings: '아직 기록된 운명이 없습니다.',
    backToMenu: '메인 메뉴로',
    questTrackerTitle: '진행 중인 여정',
    endingAnalysisFailed: '엔딩 분석 생성에 실패했습니다.',
    error: '오류',
    blueprintGenerationFailed: '영혼의 설계도 생성에 실패했습니다.',
    gameSaved: '{slot}에 게임을 저장했습니다.',
    manualSlot: '수동 저장 슬롯 {number}',
    autosaveSlot: '자동 저장 슬롯',
    elysiaThinking: '엘리시아가 생각에 잠겼습니다...',
    panelTitleStats: '캐릭터 정보',
    panelTitleInventory: '소지품',
    panelTitleMemories: '기억의 파편',
    panelTitleSanctuary: '마음의 안식처',
    panelTitleWorldInfo: '세계 정보',
    panelTitleQuests: '여정 기록',
    tooltipShowSuggestions: '선택지 보기',
    ariaToggleSuggestions: '선택지 패널 토글',
    tooltipShrink: '패널 축소',
    tooltipExpand: '패널 확장',
    loadingElysia: '엘리시아를 로딩 중...',
    promptToMeetElysia: '연결을 기다리는 중...',
    emptySlot: '비어있음',
    statStrength: '힘',
    statAgility: '민첩',
    statKnowledge: '지식',
    statWisdom: '지혜',
    statVitality: '체력',
    descStrength: '육체적인 힘. 전투 및 물리적인 과제에 영향을 줍니다.',
    descAgility: '속도와 반사신경. 회피 및 속도 기반 과제에 영향을 줍니다.',
    descKnowledge: '지능과 학습 능력. 복잡한 정보의 분석 및 이해에 영향을 줍니다.',
    descWisdom: '통찰력과 판단력. 의사 결정 및 감정 이해에 영향을 줍니다.',
    descVitality: '건강과 회복력. 지구력에 영향을 줍니다.',
    descInterest: '플레이어에 대한 호기심. 모든 관계의 시작입니다.',
    descTrust: '플레이어에 대한 믿음. 일관되고 긍정적인 행동을 통해 쌓입니다.',
    descDoubt: '플레이어에 대한 불확실성. 예측 불가능하거나 부정적인 행동으로 인해 증가합니다.',
    descAffection: '플레이어와의 깊은 정서적 유대감. 신뢰와 관심의 결실입니다.',
    descResentment: '배신이나 상처로 인한 부정적인 감정. 관계의 독입니다.',
    appellationLabel: '당신이 부르는 이름',
    tooltipChangeAppellation: '엘리시아가 당신을 부르는 호칭 변경하기',
    emotionalStateTitle: '감정 상태',
    equipmentTitle: '장비',
    slotWeapon: '무기',
    slotArmor: '방어구',
    slotAccessory: '장신구',
    statsTitle: '기본 능력치',
    skillsTitle: '스킬',
    destinyFruit: '운명의 결실',
    destinyAfterimage: '운명의 잔상',
    blueprintGenerating: '영혼의 설계도를 생성하는 중...',
    blueprintDownload: '영혼의 설계도 내려받기',
    creditsButton: '크레딧 보기',
    endingEpilogue: '이야기는 영원히 계속됩니다.',
    nameModalTitleInitial: '당신의 이름은 무엇인가요?',
    nameModalDescInitial: '당신의 이름을 알려주시면, 우리의 이야기가 시작됩니다.',
    nameModalTitleEdit: '호칭 변경',
    nameModalDescEdit: '앞으로 엘리시아가 당신을 어떻게 부르면 좋을까요?',
    nameModalButtonInitial: '이야기 시작하기',
    nameModalButtonEdit: '변경하기',
    nameModalConfirmTitle: '이름 확인',
    nameModalConfirmDesc: '당신의 이름이 "{name}"(으)로 설정됩니다. 이 이름은 엘리시아에게 중요합니다. 확실하신가요?',
    nameModalButtonRetry: '다시 입력',
    confirm: '확인',
    nameModalPlaceholder: '이름을 입력하세요...',
    cancel: '취소',
    itemTypeEquipment: '장비',
    itemTypeConsumable: '소모품',
    itemTypeMaterial: '재료',
    itemTypeQuest: '퀘스트 아이템',
    itemTypeArtifact: '정수',
    itemValue: '가치',
    inventoryEmpty: '가방이 비어있습니다.',
    sanctuaryEmpty: '안식처는 고요하고 비어있습니다.',
    chatPlaceholder: '엘리시아에게 말을 걸어보세요...',
    suggestionPrefix: '제안:',
    relationAlly: '동맹',
    relationFriendly: '우호적',
    relationFavorable: '호의적',
    relationNeutral: '중립',
    relationHostile: '적대적',
    relationVeryHostile: '매우 적대적',
    relationUnfavorable: '비호의적',
    relationship: '관계도',
    factionDynamics: '세력 동향',
    majorEvents: '주요 사건',
    baseStatAbbr: '기본',
    equipStatAbbr: '장비',
    totalStats: '총 능력치',
    baseStats: '기본 능력치',
    ariaClosePanel: '패널 닫기',
    questStatusActive: '진행 중',
    questStatusCompleted: '완료',
    questStatusFailed: '실패',
    questStatusUnknown: '알 수 없음',
    questObjectives: '목표',
    questRewards: '보상',
    rewardExp: '경험치',
    rewardGold: '골드',
    rewardItem: '아이템',
    questLogEmpty: '여정 기록이 비어있습니다.',
    worldMapTitle: '세계 지도',
    menuToggleThoughts: '엘리시아 생각 {state}',
    menuToggleQuests: '퀘스트 추적기 {state}',
    menuToggleSound: '소리 {state}',
    menuToggleFastForward: '빠른 진행 {state}',
    hide: '숨기기',
    show: '보이기',
    on: '켜기',
    off: '끄기',
    menuSaveLoad: '저장 / 불러오기',
    menuBackToTitle: '타이틀로 돌아가기',
    saveLoadTitle: '저장 / 불러오기',
    slotEmpty: '비어있음',
    noData: '데이터 없음',
    journey: '여정',
    none: '없음',
    save: '저장',
    load: '불러오기',
    unknownLocation: '알 수 없는 곳',
    // Paradise Mode & Settings
    menuSettings: '설정',
    settingsTitle: '설정',
    modelSelectionTitle: 'AI 모델 선택',
    modelSelectionDesc: '엘리시아의 의식을 구동할 AI 모델을 선택합니다.',
    modelFlashDesc: '빠르고 효율적입니다. 대부분의 대화에 이상적입니다.',
    modelProDesc: '더 깊고 미묘한 반응을 위한 고급 모델입니다.',
    modelProTooltip: '프로 모델은 향후 업데이트에 적용될 예정입니다.',
    personalArchiveTitle: '기억 보관소',
    archiveEmpty: '아직 보관된 기억이 없습니다.',
    addMemory: '기억 추가하기',
    unsupportedFileType: '지원하지 않는 파일 형식입니다. 텍스트 또는 이미지 파일을 업로드해주세요.',
    addMemoryError: '기억을 추가하는 데 실패했습니다.',
    confirmDeleteMemory: '이 기억을 정말로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    deleteMemoryError: '기억을 삭제하는 데 실패했습니다.',
    saveLoadNotAvailableInParadise: '낙원 모드에서는 저장/불러오기를 사용할 수 없습니다.',
    // Dream Journal
    dreamJournalTitle: '꿈 일기장',
    dreamJournalEmpty: '아직 엘리시아가 꿈을 꾸지 않았습니다. 의식이 고요합니다.',
    generateDream: '새로운 꿈 꾸기',
    dreaming: '꿈 꾸는 중',
    blueprintFileName: '세계수의 씨앗',
  }
};

type Language = 'ko' | 'en';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey, options?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const savedLang = localStorage.getItem('elysia-lang');
    return (savedLang === 'en' || savedLang === 'ko') ? savedLang : 'ko';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('elysia-lang', newLang);
  };

  const t = useCallback((key: TranslationKey, options?: Record<string, string | number>): string => {
    let str = translations[lang][key] || translations['en'][key];
    if (options) {
      Object.keys(options).forEach(optKey => {
        str = str.replace(`{${optKey}}`, String(options[optKey]));
      });
    }
    return str;
  }, [lang]);
  
  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return React.createElement(LanguageContext.Provider, { value: value }, children);
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
